OUTPUT_DIR = "outputs"
OUTPUT_DIR_HISTORY = "outputs/history"
OUTPUT_DIR_CURRENT = "outputs/current"
URL_PREFIX = "/gesellschaft/markus-lanz/markus-lanz-vom"
URL_EXPORT_NAME = "found_urls.json"
URL_EXPORT_PATH = f"{OUTPUT_DIR_HISTORY}/{URL_EXPORT_NAME}"
