from scrapy.http import Response
from scrapy.loader import ItemLoader

from lanz_mining.miner.items import LanzEpisodeItem, IllnerEpisodeItem


def parse_illner_episode(response: Response, debug: bool) -> IllnerEpisodeItem:
    from icecream import ic

    details_div = '//div[@class="details cell medium-7 large-8"]'
    teaser_info_div = '/div[@class="other-infos"]/dl/dd[@class="teaser-info"]'
    name_select = '//h1[@id="main-content"]/text()'
    date_select = f"{details_div}{teaser_info_div}[2]/text()"
    length_select = f"{details_div}{teaser_info_div}[1]/text()"
    description_select = f'{details_div}/p[@class="item-description"]/text()'
    factcheck_select = f'//div[@class="b-post-content"]/section[@class="b-group-contentbox"]/div/div/h3/text()'

    loader = ItemLoader(item=IllnerEpisodeItem(), response=response)
    loader.add_xpath("name", name_select)
    loader.add_xpath("date", date_select)
    loader.add_xpath("length", length_select)
    description = response.xpath(description_select).get().strip()
    extended_desc = get_illner_extended_decription(response).strip()
    description += f" {extended_desc}"
    loader.add_value("description", description)
    loader.add_xpath("factcheck", factcheck_select)
    guests_div = '//article[@class="b-group-persons"]/div/div/ul/li'
    names = response.xpath(f'{guests_div}/div/div[@class="guest-text"]/h3/button/text()').getall()
    roles = response.xpath(f'{guests_div}/div/div[@class="guest-text"]/div/p/text()').getall()
    guests: list[dict] = []
    for i, n in enumerate(names):
        r = roles[i] if i <= len(roles) else None  # Just in case
        guests.append({"name": n.strip(), "role": r.strip()})

    loader.add_value("guests", guests)
    item = loader.load_item()
    if debug:
        ic(item)
    return item


def get_illner_extended_decription(response: Response) -> str:
    description_extend_select = f'//div[@class="b-post-content"]/div/div/p/text()'
    extended_desc = []
    for p in response.xpath(description_extend_select).getall():
        if '"maybrit illner"' not in p:
            extended_desc.append(p)
        else:
            # Need to stop, beacuse we hit autogenerated content.
            break
    return " ".join(extended_desc)


def parse_lanz_episode(response: Response, debug: bool) -> LanzEpisodeItem:
    details_div = '//div[@class="details cell medium-7 large-8"]'
    teaser_info_div = '/div[@class="other-infos"]/dl/dd[@class="teaser-info"]'
    loader = ItemLoader(item=LanzEpisodeItem(), response=response)
    loader.add_xpath("name", '//h1[@id="main-content"]/text()')
    loader.add_xpath("date", f"{details_div}{teaser_info_div}[2]/text()")
    loader.add_xpath("length", f"{details_div}{teaser_info_div}[1]/text()")
    loader.add_xpath("description", f'{details_div}/p[@class="item-description"]/text()')
    guests_div = '//div[@class="b-post-content"]/div/div'
    # participants_loader = loader.nested_xpath(participants_div)

    p_texts = response.xpath(f"{guests_div}/p/text()").getall()
    p_texts = [  # remove empty sets of random artifacts
        pt.strip() for pt in p_texts if len(pt.strip()) > 0
    ]
    all_guests = response.xpath(f"{guests_div}/p/b/text()").getall()
    if len(all_guests) < 1:
        all_guests = response.xpath(f"{guests_div}/p/strong/text()").getall()
    guests = map_lanz_guests(all_guests, p_texts, response)
    loader.add_value("guests", guests)
    item = loader.load_item()
    if debug:
        print(item)
    return item


def map_lanz_guests(all_guests: str, texts: list[str], response: Response) -> list[dict]:
    guests = []
    for i, guest in enumerate(all_guests):
        try:
            name, role = guest.split(",")
        except ValueError as _:
            name = response.xpath('//h1[@id="main-content"]/text()').get()
            print(_)
            print(name)
            print(guest)
            name, role = guest, "None"
        try:
            text = texts[i]
        except IndexError as _:
            print(_)
            text = ""

        guests.append({"name": name.strip(), "role": role.strip(), "text": text})
    return guests
