name = "Minimal Vis Theme"
license = "MIT"
licenselink = "https://github.com/arrrrrmin/lanz-mining"
description = "Simple theme for data visualizations, with hugo and d3js."
homepage = "https://arrrrrmin.github.io/lanz-mining/"

[author]
  name = "arrrrrmin"
  homepage = "https://github.com/arrrrrmin/"

