baseURL = 'https://example.org/'
languageCode = 'de-de'
title = 'Lanz mining'
theme = 'minimal-vis-theme'

[[menus.main]]
name = 'Details'
pageRef = '/details'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20