# Party membership mapping aims to resolve the fuzzy role "politician".

from datetime import date

from misc import Party


TODAY = date.today().strftime("%Y-%m-%d")

# Map of names to political party membership
PARTY_MEMBERSHIP_MAP = {
    "Alexander Graf Lambsdorff": Party.FDP,
    "Aminata Touré": Party.B90G,
    "Andreas Bovenschulte": Party.SPD,
    "Anton Hofreiter": Party.B90G,
    "Belit Onay": Party.B90G,
    "Bernd Riexinger": Party.LINKE,
    "Bettina Stark Watzinger": Party.FDP,
    "Boris Pistorius": Party.SPD,
    "Carsten Linnemann": Party.CDU,
    "Cem Özdemir": Party.B90G,
    "Christian Dürr": Party.FDP,
    "Christoph Ploß": Party.CDU,
    "Claus Ruhe Madsen": Party.NP,
    "Daniel Günther": Party.CDU,
    "Diana Kinnert": Party.CDU,
    "Dietmar Bartsch": Party.LINKE,
    "Franziska Giffey": Party.SPD,
    "Gerhart Baum": Party.FDP,
    "Gregor Gysi": Party.LINKE,
    "Hubert Aiwanger": Party.FW,
    "Hubertus Heil": Party.SPD,
    "Jan van Aken": Party.LINKE,
    "Janine Wissler": Party.LINKE,
    "Jens Spahn": Party.CDU,
    "Joe Chialo": Party.CDU,
    "Johannes Vogel": Party.FDP,
    "Johannes Winkel": Party.CDU,
    "Jürgen Trittin": Party.B90G,
    "Kai Wegner": Party.CDU,
    "Karin Prien": Party.CDU,
    "Karl Lauterbach": Party.SPD,
    "Katja Kipping": Party.LINKE,
    "Kevin Kühnert": Party.SPD,
    "Klara Geywitz": Party.SPD,
    "Klaus von Dohnanyi": Party.SPD,
    "Konstantin Kuhle": Party.FDP,
    "Lars Klingbeil": Party.SPD,
    "Linda Teuteberg": Party.FDP,
    "Marie Agnes Strack Zimmermann": Party.FDP,
    "Manfred Weber": Party.CSU,
    "Marco Buschmann": Party.FDP,
    "Markus Söder": Party.CSU,
    "Martin Huber": Party.CSU,
    "Michael Roth": Party.SPD,
    "Michael Theurer": Party.FDP,
    "Nancy Faeser": Party.SPD,
    "Norbert Röttgen": Party.CDU,
    "Omid Nouripour": Party.B90G,
    "Paul Ziemiak": Party.CDU,
    "Peter Altmaier": Party.CDU,
    "Ralf Stegner": Party.SPD,
    "Reiner Haseloff": Party.CDU,
    "Ricarda Lang": Party.B90G,
    "Robert Habeck": Party.B90G,
    "Robert Lambrou": Party.AFD,
    "Roderich Kiesewetter": Party.CDU,
    "Rüdiger Lucassen": Party.AFD,
    "Saskia Esken": Party.SPD,
    "Sebastian Fiedler": Party.SPD,
    "Sabine Leutheusser Schnarrenberger": Party.FDP,
    "Serap Güler": Party.CDU,
    "Sigmar Gabriel": Party.SPD,
    "Steffen Kotré": Party.AFD,
    "Steffi Lemke": Party.B90G,
    "Stephan Weil": Party.SPD,
    "Svenja Schulze": Party.SPD,
    "Theo Waigel": Party.CSU,
    "Thomas Heilmann": Party.CDU,
    "Thomas de Maizière": Party.CDU,
    "Thorsten Frei": Party.CDU,
    "Tino Chrupalla": Party.AFD,
    "Werner Henning": Party.CDU,
    "Winfried Kretschmann": Party.B90G,
    "Wolfgang Kubicki": Party.FDP,
    "Christian Engelhardt": Party.CDU,
    "Andreas Bausewein": Party.SPD,
    "Cordelia Koch": Party.B90G,
    "Sibylle Keupen": Party.NP,
    "Christian Herrgott": Party.CDU,
    "Peter Tschentscher": Party.SPD,
    "Annalena Baerbock": Party.B90G,
    "Bettina Dickes": Party.CDU,
    "Tim von Winning": Party.NP,
    "Ryyan Alshebl": Party.B90G,
    "Joachim Gauck": Party.NP,
    "Tanja Schweiger": Party.FW,
    "Jens Marco Scherf": Party.B90G,
    "Günther Martin Pauli": Party.CDU,
    "Rita Röhrl": Party.SPD,
    "Mario Czaja": Party.CDU,
    "Wolfgang Schäuble": Party.CDU,
    "Ulrike Scharf": Party.CSU,
    "Herbert Reul": Party.CDU,
    "Jessica Rosenthal": Party.SPD,
    "Michael Kretschmer": Party.CDU,
    "Verena Hubertz": Party.SPD,
    "Frank Schäffler": Party.FDP,
    "Friedrich Merz": Party.CDU,
    "Joachim Stamp": Party.FDP,
    "Mike Mohring": Party.CDU,
    "Philipp Türmer": Party.SPD,
    "Franziska Brandmann": Party.FDP,
    "Katharina Stolla": Party.B90G,
    "René Wilke": Party.LINKE,
    "Olaf von Löwis": Party.CSU,
    "Mario Voigt": Party.CDU,
    "Philipp Amthor": Party.CDU,
    "Katrin Göring Eckardt": Party.B90G,
    "Andy Grote": Party.SPD,
    "Svenja Appuhn": Party.B90G,
    "Franz Müntefering": Party.SPD,
    "Dagmar Schulz": Party.NP,
    "Oliver Schmidt Gutzat": Party.SPD,
    "Wiebke Şahin Schwarzweller": Party.FDP,
    "Bodo Ramelow": Party.LINKE,
    "Lars Bökenkröger": Party.CDU,
    "Richard Arnold": Party.CDU,
    "Felix Schwenke": Party.SPD,
    "Christine Herntier": Party.NP,
    "Yvonne Mosler": Party.B90G,
    "Fabio De Masi": Party.BSW,
    "Michael Kellner": Party.B90G,
    "Katharina Dröge": Party.B90G,
    "Andreas Audretsch": Party.B90G,
    "Marcus Faber": Party.FDP,
    "Jakob Blasel": Party.B90G,
    "Johannes Volkmann": Party.CDU,
    "Bärbel Bas": Party.SPD,
    "Peer Steinbrück": Party.SPD,
    "Klaus Müller": Party.B90G,
    "Angela Merkel": Party.CDU,
    "Felix Banaszak": Party.B90G,
    "Alexander Dobrindt": Party.CSU,
    "Anna Kassautzki": Party.SPD,
    "Jens Teutrine": Party.FDP,
    "Merle Spellerberg": Party.B90G,
    "Maximilian Mörseburg": Party.CDU,
    "Armin Laschet": Party.CDU,
    "Bijan Djir Sarai": Party.FDP,
    "Christian Lindner": Party.FDP,
    "Wolfgang Bosbach": Party.CDU,
    "Manuela Schwesig": Party.SPD,
    "Wolfgang Schmidt": Party.SPD,
    "Alexander Throm": Party.CDU,
    "Alice Weidel": Party.AFD,
    "Olaf Scholz": Party.SPD,
    "Hendrik Wüst": Party.CDU,
    "Thomas de Maizère": Party.CDU,
    "Franziska Brantner": Party.B90G,
    "Jörg Urban": Party.AFD,
    "Beatrix von Storch": Party.AFD,
    "Matthias Miersch": Party.SPD,
    "Malu Dreyer": Party.SPD,
    "Renate Künast": Party.B90G,
    "Cansel Kiziltepe": Party.SPD,
    "Armin Schuster": Party.CDU,
    "Dorothee Bär": Party.CDU,
    "Christian Leye": Party.BSW,
    "Lamya Kaddor": Party.B90G,
    "Julia Klöckner": Party.CDU,
    "Katarina Barley": Party.SPD,
    "Ines Schwerdtner": Party.LINKE,
    "Heidi Reichinnek": Party.LINKE,
    "Muhanad Al Halak": Party.FDP,
    "Hans Reichhart": Party.CSU,
    "Matthias Ecke": Party.SPD,
    "Petra Köpping": Party.SPD,
    "Katharina Schulze": Party.B90G,
    "Anke Rehlinger": Party.SPD,
    "Christian Wulff": Party.CDU,
    "Alexander Schweitzer": Party.SPD,
    "Frauke Petry": Party.NP,
    "Joschka Fischer": Party.B90G,
    "Ralph Brinkhaus": Party.CDU,
    "Achim Brötel": Party.CDU,
    "Hendrik Streeck": Party.CDU,
    "Dirk Niebel": Party.FDP,
    "Martin Schulz": Party.SPD,
    "Mirko Geißler": Party.NP,
    "Jutta Steinruck": Party.NP,
    "Thomas Jung": Party.SPD,
    "Liane Bach": Party.NP,
    "Michaela Kaniber": Party.CSU,
    "Jürgen Hardt": Party.CDU,
    "Michael Lüders": Party.BSW,
    "Ruprecht Polenz": Party.CDU,
    "Gitta Connemann": Party.CDU,
}


def get_complicated_party_memberships() -> dict[str, list[tuple[str, str, str]]]:
    """Special cases of politicians switching their party membership at some point in time."""
    return {
        "Boris Palmer": [
            ("1972-1-1", "2023-5-1", Party.B90G),
            ("2023-5-1", TODAY, Party.NP),
        ],
        "Claus R Madsen": [
            ("1972-1-1", "2023-5-1", Party.NP),
            ("2023-5-1", TODAY, Party.CDU),
        ],
        "Jörg Meuthen": [
            ("2015-7-1", "2022-1-28", Party.AFD),
            ("2022-1-28", TODAY, Party.NP),
        ],
        "Sahra Wagenknecht": [
            ("1969-7-1", "2024-1-8", Party.LINKE),
            ("2024-1-8", TODAY, "BSW"),
        ],
        "Oskar Lafontaine": [
            ("1985-1-1", "2024-1-8", Party.LINKE),
            ("2024-1-8", TODAY, "BSW"),
        ],
        "Ursula Baum": [
            ("2004-1-1", "2014-1-1", Party.CDU),
            ("2014-1-1", TODAY, Party.NP),
        ],
        "Dirk Neubauer": [
            ("2017-1-1", "2021-1-1", Party.SPD),
            ("2021-1-1", TODAY, Party.NP),
        ],
        "Katja Wolf": [
            ("1999-1-1", "2024-1-30", Party.LINKE),
            ("2024-2-1", TODAY, Party.BSW),
        ],
        "Amira Mohamed Ali": [
            ("2015-1-1", "2024-1-30", Party.LINKE),
            ("2024-2-1", TODAY, Party.BSW),
        ],
        "Melis Sekmen": [
            ("1993-9-26", "2024-5-30", Party.B90G),
            ("2024-6-1", TODAY, Party.CDU),
        ],
        "Volker Wissing": [
            ("1998-1-1", "2024-11-6", Party.FDP),
            ("2024-11-6", TODAY, Party.NP),
        ],
        "Stefan Kerth": [
            ("2007-1-1", "2023-1-1", Party.SPD),
            ("2023-1-2", TODAY, Party.NP),
        ],
    }


def get_known_politicians() -> list[str]:
    """Returns all names of listed politicians"""
    list_of_politicians = list(PARTY_MEMBERSHIP_MAP.keys())
    list_of_politicians.extend(list(get_complicated_party_memberships().keys()))
    return list(set(list_of_politicians))
