# Roles mapping aims to resolve the diverse number of arbitary roles applied to people.
# Goal is to find aggreagtions that describe the data properly, without getting to detailed.
from misc import Group
from process.mappings.utils import as_rpattern


group_activism_kws = [
    "aktivist",
    "whistleblow",
    "nawalny",
    "boris-nemzow",
    "kreml-kritiker",
    "wwf",
    "letzte generation",
    "oppositionelle",
    "zeitzeuge",
    "zeitzeugin",
    "trumpist"
]
# group_history_kws = ["historiker", "zeitzeuge", "zeitzeugin", "shoah", "holocaustüberlebende"]
group_social_kws = [
    "soziolog",
    "sozialwissenschaft",
    "sozialpsycholog",
    "sozialarbeiter",
    "sprecher der arche",
    "sprecherin der arche",
    "sozialverband",
    "tafel deutschland",
    "a place for kids",
    "one billion rising",
    "jugendforscher",
]
group_education_kws = [
    "bildung",
    "lehrer",
    "pädagog",
    "schüler",
    "student",
    "schulleiter",
    "pädagog",
]
group_health_kws = [
    "arzt",
    "ärztin",
    "pharmazeut",
    "psychiater",
    "mediziner",
    "virolog",
    "psycholog",
    "gynäkolog",
    "pharmakolog",
    "gesundheit",
    "radiolog",
    "suchtexpert",
    "onkologe",
    "epidemiolog",
    "sanitäter",
    "medizinethikerin",
    "hertie-stiftung",
]
group_domestic_kws = [
    "sicherheitsexpert",
    "innere sicherheit",
    "sicherheitskonferenz",
    "polizei",
    "polizist",
    "kriminal",
    "migrationsexpert",
    "integrationsexpert",
    "kriminolog",
    "integration",
    "flüchtlingsrat",
    "migration",
]
group_military_kws = [
    "militär",
    "verteidigung",
    "bundeswehr",
    "(oberst($| (a.d.)))",
    "agent",
    "leutnat",
    "kommandierende",
    "berufssoldat",
]
group_law_kws = [
    "jurist",
    "((?<!schieds)richter(?!statter))",  # ! kriegsberichterstatter, schiedsrichter
    "rechtsanwalt",
    "rechtsanwältin",
    "anwältin",
    "anwalt",
    "steuerexpert",
    "rechtsexpert",
    "rechtswissenschaft",
    "völkerrechtler",
    "bürgerrechtler",
]
group_science_kws = [
    "klimaforscher",
    "physiker",
    "biolog",
    "hydrologe",
    "ökolog",
    "meteorolog",
    "neurowissenschaftler*",
]
group_humanities_kw = [
    "philosoph",
    "politolog*",
    "politikwissenschaft",
    "islamwissenschaft",
    "extremismusforscher",
    "generationenforscher",
    "demokratieforscher",
    "zukunftsforscher",
    "theolog*",
    "historiker",
    "konfliktforschung",
    "hudson institute",
]
group_culture_kws = [
    "autor",  # not journalist
    # "autor(in)*(?![^.]{0,40}journalist(in)*)"
    "schriftsteller",
    "publizist",
    "schauspieler",
    "musiker",
    "regisseur",
    "produzent",
    "sänger",
    "kulturwissenschaft",
    "kabarettist",
    # "moderator(in)*(?![^.]{0,40}journalist(in)*)",
    "moderator",
]
group_international_kws = [
    "afrika",
    "asien",
    "china",
    "russland",
    "iran-expert",
    "amerika",
    "usa-expert",
    "nahost",
    "botschafter",
    "ukrain",
    "frankreich",
    "osteuropa",
    "türkei",
    "diplomat",
    "islam-expert",
    "kiew",
    "united states",
    "europa-expert",
    "msc-stiftungsrats",
    "münchner sicherheitskonferenz",
    "außen- und sicherheitspolitik",
    "internationale beziehungen",
    "transatlantische beziehungen",
]
group_economy_kws = [
    "wirtschaft",
    "ökonom",
    "vw-vorstand",
    "intel-vorstand",
    "siemens-vorstand",
    "ex.*vorstand",
    "ex.*chef",
    "geschäftsführer.+betriebs",
    "manager",
    "industrie",
    "unternehmer",
    "unternehmensberater",
    "volkswirt",
    "zentralverbandes des deutschen handwerks",
    "industrie",
    "autoexperte",
    "aufsichtsratsvorsitzende.+ ag",
    "geschäftsführe.+ gmbh",
    "investor",
    "vizepräsident verband deutscher maschinen- und anlagenbau",
    "trigema",
    "stahlwille",
    "arbeitgeberverband",
    "europäischen zentralbank",
    "ig[\ |\-]metall",
    "gewerkschaftsbund",
]
group_journalist_kws = [
    "reporter",
    "journalist",
    "korrespondent",
    "kolumnist",
    "redakteur",
    "redaktion",
    "zdf",
    "ard",
    "hauptstadtbüro",
    "ressort",
    "herausgeber",
    "politik-expert",
    "rheinische post",
    "chefredakteur",
    "leiter des parlamentsbüros",
    "leiterin des parlamentsbüros",
    "bild-zeitung",
    "der freitag",
    "axel-springer",
]

group_sports_kws = [
    "fußball",
    "nationalspieler",
    "nationalspieler",
    "schiedsrichter",
    "weltmeister",
    "boxer",
    "sportschau",
    "fanverband",
    "europameister",
    "skirennläufer",
    "para-*",
]

GROUP_MAPS: dict[str, str] = {
    Group.Activism: as_rpattern(group_activism_kws),
    # Group.History: as_rpattern(group_history_kws),
    Group.Social: as_rpattern(group_social_kws),
    Group.Law: as_rpattern(group_law_kws),
    Group.Education: as_rpattern(group_education_kws),
    Group.Health: as_rpattern(group_health_kws),
    Group.International: as_rpattern(group_international_kws),
    Group.Domestic: as_rpattern(group_domestic_kws),
    Group.Military: as_rpattern(group_military_kws),
    Group.Economy: as_rpattern(group_economy_kws),
    Group.Humanities: as_rpattern(group_humanities_kw),
    # Group.Science: as_rpattern(group_science_kws),
    Group.Journalist: as_rpattern(group_journalist_kws),
    Group.Culture: as_rpattern(group_culture_kws),
    Group.Sports: as_rpattern(group_sports_kws),
    # Group.Politician: group_politician_kws,
}
